name: Deploy Backend
on:
  push:
    paths:
      - 'wallet-backend/**' # Runs only when backend code changes
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-north-1 

      - name: Build and Zip
        run: |
          cd wallet-backend
          npm install --production
          zip -r ../backend.zip .

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name wallet-backend-api \
            --zip-file fileb://backend.zip
